services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=thread_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes:
      - thread_db:/var/lib/postgresql/data # Mount the volume to PostgreSQL's data directory

volumes:
  thread_db:
    driver: local