"use client";

import { Provider, useSelector } from 'react-redux';
import InputForm from '../app/components/form/InputForm';
import { store } from '../app/store/store';
import ThreadList from '@/app/components/ThreadList';
import { NextPage } from 'next';
import BottomNavbar from '@/app/components/navbar/BottomNavbar';
import Head from 'next/head'

const Home: NextPage = () => {

  return (
    <div className="page">
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-home">
        <ThreadList isMePage={false} />
        <BottomNavbar />
        <InputForm />
      </main>
    </div>
  );
}

export default Home;
